### ISSUE TITLE
STYLING: Style account form pages

### ISSUE THREAD

**Issue by ogc1231** [ogc1231/sound-burger#29]
**Tasks**
- [x] Style Sign Up page
- [x] Style Login page
- [x]  Style Logout page
- [x] Style Password Reset page
